# Site settings
title: Park.AI 
description: Artificial intelligence optimized enforcement of on-street parking
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Park.AI
user_description: Parking violations are a problem common to most Urban areas in UAE. Park.AI aims to solve this problem with the use of Artificial intelligence optimized enforcement of on-street parking.
user_title: Artificial intelligence optimized enforcement of on-street parking
email: 
github_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
